apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  namespace: homework
spec:
  selector:
    matchLabels:
      app: home-deployment
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: home-deployment
    spec:
      initContainers:
      - name: home-deployment
        image: busybox
        volumeMounts:
        - name: homework-volume
          mountPath: "/init"
        command: ["/bin/sh", "-c"]
        args:
        - env > /init/index.html
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: homework-volume
          mountPath: /homework
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        lifecycle:
          preStop:
            exec:
              command: ["rm", "-f", "/homework/index.html"]
        livenessProbe:
          exec:
            command:
            - cat
            - /homework/index.html
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: homework-volume
        hostPath:
          path: /homework
          type: DirectoryOrCreate
      - name: nginx-config-volume
        configMap:
          name: nginx-conf
          items:
          - key: default.conf
            path: default.conf
