apiVersion: v1
kind: Pod
metadata:
  name: nginx-first-pod
  namespace: homework
spec:
  initContainers:
  - name: init-web-container
    image: busybox
    volumeMounts:
    - name: homework-volume
      mountPath: "/init"
    command: ["/bin/sh", "-c"]
    args:
    - env > /init/index.html
  containers:
  - name: nginx
    image: nginx:1.16.1
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: homework-volume
      mountPath: /homework
    - name: nginx-config-volume
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
      readOnly: true
    lifecycle:
      preStop:
        exec:
          command: ["rm", "-f", "/homework/index.html"]
  volumes:
  - name: homework-volume
    hostPath:
      path: /homework
      type: DirectoryOrCreate
  - name: nginx-config-volume
    configMap:
      name: nginx-conf
      items:
      - key: default.conf
        path: default.conf
